version: '3.7'

x-default-logging: &default
  {}

x-loki-logging: &loki
  driver: loki
  options:
    loki-url: ${LOKI_URL:?}
    mode: non-blocking
    max-buffer-size: 4m
    loki-retries: "3"

x-log-config: &log-config
  # update this value to *loki if needed to see logs in grafana dashboard.
  <<: *default

services:

  proxy:
    image: 'bahmni/proxy:${PROXY_IMAGE_TAG:?}'
    ports:
      - '80:80'
      - '443:443'
    logging: *log-config
    restart: ${RESTART_POLICY}
    environment:
      TZ: ${TZ}

  bahmni-config:
    image: 'bahmni/standard-config:${CONFIG_IMAGE_TAG:?}'
    volumes:
      - '${CONFIG_VOLUME:?}:/usr/local/bahmni_config'
    logging: *log-config
    restart: ${RESTART_POLICY}

  odoo:
    profiles: ["odoo","bahmni-standard"]
    image: 'bahmni/odoo-16:${ODOO_IMAGE_TAG:?[ERROR]}'
    ports:
      - '8069:8069'
    volumes:
      - odooappdata:/var/lib/odoo
      - ${EXTRA_ADDONS_PATH}:/mnt/extra-addons
      - odoofilestore:/var/lib/odoo/filestore
      - odooconfig:/etc/odoo
    depends_on:
      odoodb:
        condition: service_healthy
    environment:
      TZ: ${TZ}
      HOST: ${ODOO_DB_HOST}
      USER: ${ODOO_DB_USER}
      PASSWORD: ${ODOO_DB_PASSWORD}
    logging: *log-config
    restart: ${RESTART_POLICY}

  odoodb:
    profiles: ["odoo","bahmni-standard"]
    image: '${ODOO_DB_IMAGE_NAME:?[ERROR]}'
    volumes:
      - 'odoodbdata:/var/lib/postgresql/data'
      - 'odoofilestore:/filestore:ro'
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -h localhost -U odoo']
      interval: 10s
      timeout: 5s
      retries: 10
    environment:
      TZ: ${TZ}
      POSTGRES_DB: ${ODOO_DB_NAME:?}
      POSTGRES_PASSWORD: ${ODOO_DB_PASSWORD}
      POSTGRES_USER: ${ODOO_DB_USER}
    logging: *log-config
    restart: ${RESTART_POLICY}

  odoo-connect:
    profiles: ["odoo","bahmni-standard"]
    image: 'bahmni/odoo-connect:${ODOO_CONNECT_IMAGE_TAG:?[ERROR]}'
    environment:
      TZ: ${TZ}
      IS_ODOO_16: true
      ODOO_DB_SERVER: ${ODOO_DB_HOST}
      ODOO_DB_USERNAME: ${ODOO_DB_USER:?}
      ODOO_DB_PASSWORD: ${ODOO_DB_PASSWORD:?}
      OPENMRS_HOST: ${OPENMRS_HOST:?}
      OPENMRS_PORT: ${OPENMRS_PORT:?}
      OPENMRS_ATOMFEED_USER: ${OPENMRS_ATOMFEED_USER:?}
      OPENMRS_ATOMFEED_PASSWORD: ${OPENMRS_ATOMFEED_PASSWORD:?}
    depends_on:
      odoodb:
        condition: service_healthy
    logging: *log-config
    restart: ${RESTART_POLICY}

  openmrs:
    profiles: ["emr","bahmni-standard"]
    image: bahmni/openmrs:${OPENMRS_IMAGE_TAG:?}
    environment:
      TZ: ${TZ}
      OMRS_DB_NAME: ${OPENMRS_DB_NAME:?}
      OMRS_DB_HOSTNAME: ${OPENMRS_DB_HOST:?}
      OMRS_DB_USERNAME: ${OPENMRS_DB_USERNAME:?}
      OMRS_DB_PASSWORD: ${OPENMRS_DB_PASSWORD:?}
      OMRS_CREATE_TABLES: ${OPENMRS_DB_CREATE_TABLES}
      OMRS_AUTO_UPDATE_DATABASE: ${OPENMRS_DB_AUTO_UPDATE}
      OMRS_MODULE_WEB_ADMIN: ${OPENMRS_MODULE_WEB_ADMIN}
      OMRS_JAVA_SERVER_OPTS: ${OMRS_JAVA_SERVER_OPTS}
      OMRS_JAVA_MEMORY_OPTS: ${OMRS_JAVA_MEMORY_OPTS}
      SEND_MAIL: ${SEND_MAIL}
      MAIL_TRANSPORT_PROTOCOL: ${MAIL_TRANSPORT_PROTOCOL}
      MAIL_SMTP_HOST: ${MAIL_SMTP_HOST}
      MAIL_SMTP_PORT: ${MAIL_SMTP_PORT}
      MAIL_SMTP_AUTH: ${MAIL_SMTP_AUTH}
      MAIL_SMTP_STARTTLS_ENABLE: ${MAIL_SMTP_STARTTLS_ENABLE}
      MAIL_SMTP_SSL_ENABLE: ${MAIL_SMTP_SSL_ENABLE}
      MAIL_DEBUG: ${MAIL_DEBUG}
      MAIL_FROM: ${MAIL_FROM}
      MAIL_USER: ${MAIL_USER}
      MAIL_PASSWORD: ${MAIL_PASSWORD}
    volumes:
      - "${CONFIG_VOLUME:?}:/etc/bahmni_config/:ro"
      - 'bahmni-patient-images:/home/bahmni/patient_images'
      - 'bahmni-document-images:/home/bahmni/document_images'
      - 'bahmni-clinical-forms:/home/bahmni/clinical_forms'
      - 'configuration_checksums:/openmrs/data/configuration_checksums'
    depends_on:
      - openmrsdb
    logging: *log-config
    restart: ${RESTART_POLICY}

  openmrsdb:
    image: ${OPENMRS_DB_IMAGE_NAME:?}
    restart: always
    profiles: ["emr","bahmni-standard"]
    command: "--sql-mode=${OPENMRS_DB_SQL_MODES:?}"
    environment:
      TZ: ${TZ}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:?}
      MYSQL_DATABASE: ${OPENMRS_DB_NAME:?}
      MYSQL_USER: ${OPENMRS_DB_USERNAME:?}
      MYSQL_PASSWORD: ${OPENMRS_DB_PASSWORD:?}
    volumes:
      - 'openmrsdbdata:/var/lib/mysql'
    logging: *log-config

  bahmni-web:
    image: bahmni/bahmni-web:${BAHMNI_WEB_IMAGE_TAG:?}
    profiles: ["emr","bahmni-standard"]
    volumes:
      - "${CONFIG_VOLUME:?}:/usr/local/apache2/htdocs/bahmni_config/:ro"
    logging: *log-config
    restart: ${RESTART_POLICY}

  implementer-interface:
    image: bahmni/implementer-interface:${IMPLEMENTER_INTERFACE_IMAGE_TAG:?}
    profiles: ["implementer-interface","emr","bahmni-standard"]
    depends_on:
      - openmrs
    logging: *log-config
    restart: ${RESTART_POLICY}

  reports:
    image: bahmni/reports:${REPORTS_IMAGE_TAG:?}
    profiles: ["reports","bahmni-standard"]
    environment:
      TZ: ${TZ}
      OPENMRS_DB_HOST: ${OPENMRS_DB_HOST:?}
      OPENMRS_DB_NAME: ${OPENMRS_DB_NAME:?}
      OPENMRS_DB_USERNAME: ${OPENMRS_DB_USERNAME:?}
      OPENMRS_DB_PASSWORD: ${OPENMRS_DB_PASSWORD:?}
      OPENMRS_HOST: ${OPENMRS_HOST:?}
      OPENMRS_PORT: ${OPENMRS_PORT:?}
      REPORTS_DB_SERVER: reportsdb
      REPORTS_DB_NAME: ${REPORTS_DB_NAME:?}
      REPORTS_DB_USERNAME: ${REPORTS_DB_USERNAME:?}
      REPORTS_DB_PASSWORD: ${REPORTS_DB_PASSWORD:?}
      ODOO_DB_SERVER: ${ODOO_DB_HOST:?}
      ODOO_DB_NAME: ${ODOO_DB_NAME:?}
      ODOO_DB_USERNAME: ${ODOO_DB_USER:?}
      ODOO_DB_PASSWORD: ${ODOO_DB_PASSWORD:?}
      ICD10_LITE_INDICATOR: ${ICD10_LITE_INDICATOR}
    volumes:
      - "${CONFIG_VOLUME:?}:/etc/bahmni_config/:ro"
      - "bahmni-queued-reports:/home/bahmni/reports"
    depends_on:
      - reportsdb
      - openmrsdb
      - bahmni-web
    logging: *log-config
    restart: ${RESTART_POLICY}

  reportsdb:
    platform: linux/amd64
    image: ${REPORTS_DB_IMAGE_NAME:?}
    profiles: ["reports","bahmni-standard"]
    environment:
      TZ: ${TZ}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:?}
      MYSQL_DATABASE: ${REPORTS_DB_NAME:?}
      MYSQL_USER: ${REPORTS_DB_USERNAME:?}
      MYSQL_PASSWORD: ${REPORTS_DB_PASSWORD:?}
    volumes:
      - 'reportsdbdata:/var/lib/mysql'
    logging: *log-config
    restart: ${RESTART_POLICY}

  patient-documents:
    image: 'bahmni/patient-documents:${PATIENT_DOCUMENTS_TAG:?}'
    profiles: ["emr","bahmni-standard"]
    volumes:
      - 'bahmni-document-images:/usr/share/nginx/html/document_images'
      - 'bahmni-lab-results:/usr/share/nginx/html/uploaded_results'
      - "bahmni-uploaded-files:/usr/share/nginx/html/uploaded-files"
    environment:
      TZ: ${TZ}
      OPENMRS_HOST: ${OPENMRS_HOST:?}
    depends_on:
      - openmrs
    logging: *log-config
    restart: ${RESTART_POLICY}

  appointments:
    image: bahmni/appointments:${APPOINTMENTS_IMAGE_TAG:?}
    profiles: ["emr","bahmni-standard"]
    restart: ${RESTART_POLICY}

  atomfeed-console:
    image: bahmni/atomfeed-console:${ATOMFEED_CONSOLE_IMAGE_TAG:?}
    profiles: ["atomfeed-console"]
    restart: ${RESTART_POLICY}
    environment:
      TZ: ${TZ}
      OPENMRS_DB_HOST: ${OPENMRS_DB_HOST}
      OPENMRS_DB_NAME: ${OPENMRS_DB_NAME}
      OPENMRS_DB_USERNAME: ${OPENMRS_DB_USERNAME}
      OPENMRS_DB_PASSWORD: ${OPENMRS_DB_PASSWORD}
      ODOO_DB_HOST: ${ODOO_DB_HOST}
      ODOO_DB_NAME: ${ODOO_DB_NAME}
      ODOO_DB_USER: ${ODOO_DB_USER}
      ODOO_DB_PASSWORD: ${ODOO_DB_PASSWORD}

  restore_volumes:
    image: bash:5.2.15
    profiles: ["restore"]
    command: "bash /restore_docker_volumes.sh"
    volumes:
        - "${RESTORE_ARTIFACTS_PATH}:/restore-artifacts"
        - '../backup_restore/restore_docker_volumes.sh:/restore_docker_volumes.sh'
        - 'bahmni-patient-images:/mounts/bahmni-patient-images'
        - 'bahmni-document-images:/mounts/bahmni-document-images'
        - 'bahmni-clinical-forms:/mounts/bahmni-clinical-forms'
        - 'bahmni-lab-results:/mounts/bahmni-lab-results'
        - 'bahmni-queued-reports:/mounts/bahmni-queued-reports'
        - 'bahmni-uploaded-files:/mounts/bahmni-uploaded-files'
        - 'configuration_checksums:/mounts/configuration_checksums'

  ipd:
    image: bahmni/microfrontend-ipd:${IPD_TAG:?}
    container_name: ipd
    profiles: ["emr","bahmni-standard","bahmni-mart"]
    restart: ${RESTART_POLICY}
    logging: *log-config

volumes:
  odoodbdata:
  odooappdata:
  odoofilestore:
  odooconfig:
  openmrsdbdata:
  bahmni-patient-images:
  bahmni-document-images:
  bahmni-clinical-forms:
  bahmni-config:
  bahmni-lab-results:
  bahmni-uploaded-files:
  configuration_checksums:
  bahmni-queued-reports:
  reportsdbdata:
